### ISSUE TITLE
Server Management Endpoints

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#6]
# Goals

Jobs and Workspaces:
+ Launch Severs
+ Delete Severs
+ Restart Servers

## Breakdown

Preparation
- [ ] #3 Define Swagger API Requirements
- [x] [architecture/#9](https://github.com/3Blades/architecture/issues/9) agree on restful platform

Application
- [ ] #3  Basic Restful App
- [ ] #8  Setup Tests, Coverage, Climate

Endpoints
- [ ] #5  Job Server Endpoints
- [ ] #4  Workspace Server Endpoints

**Comment by jkp85** [comment]
@jgwerner Is this still valid?

**Comment by jgwerner** [comment]
@jkp85 @johngriebel no longer valid. Closing.
